<a href="https://colab.research.google.com/github/safal-stha/numpy_exercise/blob/main/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice


In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [8]:
# Create a 1-dimensional NumPy array using np.array()
a=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
b=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a,b,c

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a.shape,a.dtype,a.size

((3,), dtype('int64'), 3)

In [11]:
# Attributes of 2-dimensional array
b.shape,b.dtype,b.size

((2, 3), dtype('int64'), 6)

In [12]:
# Attributes of 3-dimensional array
c.shape,c.dtype,c.size

((1, 3, 3), dtype('int64'), 9)

In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data=pd.DataFrame(b, columns=['A','B','C'])
data

A  B  C
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
all_ones=np.ones((10,2))
all_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# Create an array of shape (7, 2, 3) of only zeros
all_zeros=np.zeros((7,2,3))
all_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
arr=np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[9, 5],
       [0, 9],
       [0, 1],
       [5, 6],
       [5, 4],
       [2, 0],
       [1, 7]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.09214254, 0.47770228, 0.25512675, 0.75223087, 0.00571348],
       [0.99695193, 0.77258671, 0.79881318, 0.36286989, 0.80642328],
       [0.31861633, 0.77702016, 0.37167705, 0.23581553, 0.20201575]])

In [24]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

Answer: The numbers in the array are same as we have assigned 42 as the random seed which performs complex calculations to give us random numbers w.r.t the seed number ie 42.

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r1= np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
unique = np.unique(r1)
unique

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Find the 0'th index of the latest array you created
r1[0][0]

np.int64(6)

In [44]:
# Get the first 2 rows of latest array you created
r1[:2]

array([[6, 7, 4, 7, 8, 1, 6],
       [8, 5, 4, 2, 6, 6, 1]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
r1[:2,:2]

array([[6, 7],
       [8, 5]])

In [46]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
r2=np.random.randint(0,10,(3,5))
ones=np.ones((3,5))
r2,ones

(array([[2, 3, 6, 3, 8],
        [0, 7, 6, 1, 7],
        [0, 8, 8, 1, 6]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [49]:
# Add the two arrays together
sum=r2+ones
sum

array([[3., 4., 7., 4., 9.],
       [1., 8., 7., 2., 8.],
       [1., 9., 9., 2., 7.]])

In [52]:
# Create another array of ones of shape (5, 3)
ones2=np.ones((5,3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
# Try add the array of ones and the other most recent array together
sum=sum+ones2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

Answer. This error is caused by broadcasting rules that numpy uses to perform operations on arrays of different shapes. But our arrays' shapes are not compatible with it.

So we can fix it by transposing the ones array of shape (5,3) which makes it (3,5) and compatible to broadcast with array sum which also has shape (3,5).

In [54]:
# Create another array of ones of shape (3, 5)
ones3=np.ones((3,5))
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# Subtract the new array of ones from the other most recent array
sum=sum-ones3
sum

array([[2., 3., 6., 3., 8.],
       [0., 7., 6., 1., 7.],
       [0., 8., 8., 1., 6.]])

In [56]:
# Multiply the ones array with the latest array
sum=sum*ones3
sum

array([[2., 3., 6., 3., 8.],
       [0., 7., 6., 1., 7.],
       [0., 8., 8., 1., 6.]])

In [57]:
# Take the latest array to the power of 2 using '**'
sum ** 2

array([[ 4.,  9., 36.,  9., 64.],
       [ 0., 49., 36.,  1., 49.],
       [ 0., 64., 64.,  1., 36.]])

In [58]:
# Do the same thing with np.square()
np.square(sum)

array([[ 4.,  9., 36.,  9., 64.],
       [ 0., 49., 36.,  1., 49.],
       [ 0., 64., 64.,  1., 36.]])

In [59]:
# Find the mean of the latest array using np.mean()
np.mean(sum)

np.float64(4.4)

In [60]:
# Find the maximum of the latest array using np.max()
np.max(sum)

np.float64(8.0)

In [61]:
# Find the minimum of the latest array using np.min()
np.min(sum)

np.float64(0.0)

In [62]:
# Find the standard deviation of the latest array
np.std(sum)

np.float64(2.961981318869741)

In [63]:
# Find the variance of the latest array
np.var(sum)

np.float64(8.773333333333332)

In [64]:
# Reshape the latest array to (3, 5, 1)
np.reshape(sum,(3,5,1))

array([[[2.],
        [3.],
        [6.],
        [3.],
        [8.]],

       [[0.],
        [7.],
        [6.],
        [1.],
        [7.]],

       [[0.],
        [8.],
        [8.],
        [1.],
        [6.]]])

In [65]:
# Transpose the latest array
sum.T

array([[2., 0., 0.],
       [3., 7., 8.],
       [6., 6., 8.],
       [3., 1., 1.],
       [8., 7., 6.]])

What does the transpose do?

Answer. Transpose simply swaps a matrix's rows with columns.

In [70]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand1=np.random.randint(0,10,(3,3))
rand2=np.random.randint(0,10,(3,2))
rand1,rand2

(array([[6, 5, 5],
        [5, 2, 5],
        [7, 1, 4]]),
 array([[0, 0],
        [4, 2],
        [3, 2]]))

In [71]:
# Perform a dot product on the two newest arrays you created
np.dot(rand1,rand2)

array([[35, 20],
       [23, 14],
       [16, 10]])

In [72]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand3=np.random.randint(0,10,(4,3))
rand4=np.random.randint(0,10,(4,3))
rand3,rand4

(array([[0, 0, 4],
        [5, 2, 8],
        [4, 7, 0],
        [4, 2, 0]]),
 array([[3, 4, 6],
        [0, 2, 1],
        [8, 9, 5],
        [9, 2, 7]]))

In [73]:
# Perform a dot product on the two newest arrays you created
np.dot(rand3,rand4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

Answer. We can transpose the second array to match the dimension compatible for matrix multiplication and perform the matrix multiplication.

In [74]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(rand3,rand4.T)

array([[ 24,   4,  20,  28],
       [ 71,  12,  98, 105],
       [ 40,  14,  95,  50],
       [ 20,   4,  50,  40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Answer. It is because the dimension of the second array was changed to (3,4) for it to be in the form of (4 x 3) * (3 x 4) which is required for multiplication and gives 4*4 matrix.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [75]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand5=np.random.randint(0,10,(4,3))
rand6=np.random.randint(0,10,(4,3))
rand5,rand6

(array([[7, 1, 5],
        [6, 1, 9],
        [1, 9, 0],
        [7, 0, 8]]),
 array([[5, 6, 9],
        [6, 9, 2],
        [1, 8, 7],
        [9, 6, 8]]))

In [76]:
# Compare the two arrays with '>'
rand5>rand6

array([[ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

Answer. Each element is compared with the corresponding element in the next array and returns True and False.



In [77]:
# Compare the two arrays with '>='
rand5 >= rand6

array([[ True, False, False],
       [ True, False,  True],
       [ True,  True, False],
       [False, False,  True]])

In [78]:
# Find which elements of the first array are greater than 7
greater = rand5 >7
rand5[greater]

array([9, 9, 8])

In [79]:
# Which parts of each array are equal? (try using '==')
greater = rand5 == rand6
rand5[greater]

array([6, 1, 8])

In [86]:
# Sort one of the arrays you just created in ascending order
rand6,np.sort(rand6)

(array([[5, 6, 9],
        [6, 9, 2],
        [1, 8, 7],
        [9, 6, 8]]),
 array([[5, 6, 9],
        [2, 6, 9],
        [1, 7, 8],
        [6, 8, 9]]))

In [87]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand6,axis=1)

array([[0, 1, 2],
       [2, 0, 1],
       [0, 2, 1],
       [1, 2, 0]])

In [89]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand5)

np.int64(5)

In [90]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand5)

np.int64(8)

In [91]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand5,axis=1)

array([0, 2, 1, 2])

In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand5,axis=0)

array([2, 3, 2])

In [93]:
# Create an array of normally distributed random numbers
np.random.randn(3,4)

array([[-1.18326562,  0.49499565, -0.16530961, -0.68717518],
       [ 0.06835125, -0.40940883,  1.88954766, -0.67580473],
       [-0.91341254, -0.45503317, -0.41276161,  0.59564365]])

In [94]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])